# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# A coverage report will be created for the Python 3.8 version
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# pandapipes-develop branch is designed to work with pandapower-develop branch

# This is a basic workflow to help you get started with Actions

name: release_testpypi

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:
    branch: [develop]
  workflow_dispatch:
    inputs:
      python_version:
        description: 'python version'
        required: true
        default: '3.10'
        type: choice
        options:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets up python3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}

      # Installs and upgrades pip, installs other dependencies and installs the package from setup.py
      - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
        run: |
          # Upgrade pip
          python3 -m pip install --upgrade pip
          # Install twine
          python3 -m pip install setuptools wheel twine

      # Upload to TestPyPI
      - name: Build and Upload to TestPyPI
        run: |
          python3 setup.py sdist --formats=zip
          twine check dist/* --strict 
          #python3 -m twine upload dist/*

        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI }}
          TWINE_REPOSITORY: testpypi

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os:  [ ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest python-igraph pytest-split numba
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install git+https://github.com/e2nIEE/pandapower@develop#egg=pandapower
          pip install .
      - name: Install dependencies on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest python-igraph pytest-split numba
          if (Test-Path -Path requirements.txt -PathType Leaf) { pip install -r requirements.txt }
          python -m pip install git+https://github.com/e2nIEE/pandapower@develop#egg=pandapower
          pip install .
      - name: List all installed packages
        run: |
          pip list
      - name: Test with pytest
        if: ${{ matrix.python-version != '3.9' }}
        run: |
          pytest
      - name: Test with pytest and Codecov
        if: ${{ matrix.python-version == '3.9' }}
        run: |
          python -m pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.9' }}
        uses: codecov/codecov-action@v1
        with:
          verbose: true

  linting:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install git+https://github.com/e2nIEE/pandapower@develop#egg=pandapower
          pip install .
      - name: List all installed packages
        run: |
          pip list
      - name: Lint with flake8 (syntax errors and undefinded names)
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Lint with flake8 (all errors/warnings)
        run: |
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  tutorial_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os:  [ ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest nbmake pytest-xdist pytest-split python-igraph numba 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install git+https://github.com/e2nIEE/pandapower@develop#egg=pandapower
          pip install .
      - name: List all installed packages
        run: |
          pip list
      - name: Test with pytest
        run: |
          pytest --nbmake -n=auto "./tutorials"



